const Beauty = [
    {
        id: 1,
        name: "Hydrating Face Serum",
        category: "Skincare",
        price: "$29.99",
        originalPrice: "$49.99",
        discount: "40% OFF",
        rating: 4.7,
        reviewCount: 180,
        image:
            "https://images.unsplash.com/photo-1598196743856-90912f6c0f49?auto=format&fit=crop&w=400&q=80",
        tags: ["Hydrating", "Vitamin C", "Anti-Aging"],
        isNew: true,
    },
    {
        id: 2,
        name: "Matte Liquid Lipstick",
        category: "Makeup",
        price: "$15.99",
        originalPrice: "$24.99",
        discount: "36% OFF",
        rating: 4.4,
        reviewCount: 95,
        image:
            "https://images.unsplash.com/photo-1596464716121-9c199f0a4f0f?auto=format&fit=crop&w=400&q=80",
        tags: ["Long-Lasting", "Matte", "Cruelty-Free"],
        isNew: false,
    },
    {
        id: 3,
        name: "Organic Aloe Vera Gel",
        category: "Skincare",
        price: "$12.50",
        originalPrice: "$19.99",
        discount: "37% OFF",
        rating: 4.5,
        reviewCount: 140,
        image:
            "https://images.unsplash.com/photo-1591095863530-f4c0b2d94939?auto=format&fit=crop&w=400&q=80",
        tags: ["Soothing", "Moisturizing", "Vegan"],
        isNew: true,
    },
    {
        id: 4,
        name: "Rejuvenating Night Cream",
        category: "Skincare",
        price: "$34.99",
        originalPrice: "$59.99",
        discount: "42% OFF",
        rating: 4.8,
        reviewCount: 220,
        image:
            "https://images.unsplash.com/photo-1616627455693-fb1e08d51420?auto=format&fit=crop&w=400&q=80",
        tags: ["Anti-Aging", "Hydrating", "Collagen Boost"],
        isNew: false,
    },
    {
        id: 5,
        name: "Herbal Shampoo",
        category: "Haircare",
        price: "$18.99",
        originalPrice: "$29.99",
        discount: "37% OFF",
        rating: 4.6,
        reviewCount: 132,
        image:
            "https://images.unsplash.com/photo-1606813904801-f0c7b5e3e9e8?auto=format&fit=crop&w=400&q=80",
        tags: ["Natural", "Sulfate-Free", "Strengthening"],
        isNew: true,
    },
    {
        id: 6,
        name: "Nourishing Body Lotion",
        category: "Bodycare",
        price: "$14.99",
        originalPrice: "$24.99",
        discount: "40% OFF",
        rating: 4.5,
        reviewCount: 110,
        image:
            "https://images.unsplash.com/photo-1600180758895-b024ee5fa1b3?auto=format&fit=crop&w=400&q=80",
        tags: ["Moisturizing", "Non-Greasy", "Soft Skin"],
        isNew: false,
    },
    {
        id: 7,
        name: "Vitamin C Face Mask",
        category: "Skincare",
        price: "$9.99",
        originalPrice: "$14.99",
        discount: "33% OFF",
        rating: 4.4,
        reviewCount: 75,
        image:
            "https://images.unsplash.com/photo-1605902711622-cfb43c4437ff?auto=format&fit=crop&w=400&q=80",
        tags: ["Brightening", "Hydrating", "Vegan"],
        isNew: true,
    },
    {
        id: 8,
        name: "Organic Lip Balm Set",
        category: "Makeup",
        price: "$12.50",
        originalPrice: "$19.99",
        discount: "37% OFF",
        rating: 4.6,
        reviewCount: 60,
        image:
            "https://images.unsplash.com/photo-1610119281023-d1e2e3b4f682?auto=format&fit=crop&w=400&q=80",
        tags: ["Hydrating", "Organic", "Natural Flavors"],
        isNew: false,
    },
];

export default Beauty;
