const User = [
  {
    id: 1,
    name: "Apple MacBook Air M2",
    description: "13.6-inch, 8GB RAM, 256GB SSD - Midnight",
    price: 1199.99,
    originalPrice: 1299.99,
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=60",
    category: "electronics",
    inStock: true,
    isPrimeEligible: true,
    isOnSale: true,
    hasFreeShipping: true,
    rating: 4.7,
    reviewCount: 1254,
    seller: "Apple Store",
    deliveryDate: "Tomorrow",
    color: "Midnight",
    storage: "256GB SSD",
    memory: "8GB RAM",
    warranty: "1 Year Apple Care",
    lastPriceDrop: 100,
    priceDropDate: "2 days ago",
    stockLeft: 12,
    isPriceWatched: true,
    watchedPrice: 1099.99,
  },
  {
    id: 2,
    name: 'Samsung 65" 4K Smart TV',
    description: "Crystal UHD, HDR, Smart TV with Alexa Built-in",
    price: 699.99,
    originalPrice: 899.99,
    image:
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500&auto=format&fit=crop&q=60",
    category: "electronics",
    inStock: true,
    isPrimeEligible: true,
    isOnSale: true,
    hasFreeShipping: true,
    rating: 4.5,
    reviewCount: 892,
    seller: "Samsung Official",
    deliveryDate: "Friday",
    screenSize: "65 inches",
    resolution: "4K UHD",
    smartFeatures: "Alexa Built-in",
    warranty: "2 Years",
    lastPriceDrop: 200,
    priceDropDate: "1 week ago",
    stockLeft: 8,
    isPriceWatched: false,
  },
  {
    id: 3,
    name: "Nintendo Switch OLED Model",
    description: "White Console with Neon Blue & Neon Red Joy‑Con",
    price: 349.99,
    originalPrice: 349.99,
    image:
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=500&auto=format&fit=crop&q=60",
    category: "electronics",
    inStock: false,
    isPrimeEligible: false,
    isOnSale: false,
    hasFreeShipping: false,
    rating: 4.8,
    reviewCount: 2345,
    seller: "Nintendo Store",
    deliveryDate: "Out of Stock",
    color: "White",
    model: "OLED",
    includes: "2 Joy-Cons",
    warranty: "1 Year",
    lastPriceDrop: 0,
    priceDropDate: null,
    stockLeft: 0,
    isPriceWatched: true,
    watchedPrice: 299.99,
    restockDate: "Jan 25",
  },
  {
    id: 4,
    name: "Dyson V15 Detect Cordless Vacuum",
    description: "Laser dust detection, 60 mins run time",
    price: 749.99,
    originalPrice: 799.99,
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    category: "home",
    inStock: true,
    isPrimeEligible: true,
    isOnSale: true,
    hasFreeShipping: true,
    rating: 4.6,
    reviewCount: 567,
    seller: "Dyson Official",
    deliveryDate: "Tomorrow",
    type: "Cordless",
    runTime: "60 mins",
    features: "Laser detection",
    warranty: "5 Years",
    lastPriceDrop: 50,
    priceDropDate: "3 days ago",
    stockLeft: 5,
    isPriceWatched: false,
  },
  {
    id: 5,
    name: "Sony PlayStation 5 Console",
    description: "Marvel's Spider-Man 2 Bundle",
    price: 499.99,
    originalPrice: 559.99,
    image:
      "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=500&auto=format&fit=crop&q=60",
    category: "electronics",
    inStock: true,
    isPrimeEligible: true,
    isOnSale: true,
    hasFreeShipping: true,
    rating: 4.9,
    reviewCount: 1890,
    seller: "Sony Store",
    deliveryDate: "Wednesday",
    edition: "Spider-Man 2 Bundle",
    storage: "825GB SSD",
    includes: "Game + Console",
    warranty: "1 Year",
    lastPriceDrop: 60,
    priceDropDate: "Yesterday",
    stockLeft: 3,
    isPriceWatched: true,
    watchedPrice: 479.99,
  },
  {
    id: 6,
    name: "KitchenAid Artisan Stand Mixer",
    description: "5-Quart, Empire Red, Tilt-Head",
    price: 449.99,
    originalPrice: 499.99,
    image:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&auto=format&fit=crop&q=60",
    category: "home",
    inStock: true,
    isPrimeEligible: true,
    isOnSale: false,
    hasFreeShipping: true,
    rating: 4.7,
    reviewCount: 1234,
    seller: "KitchenAid Store",
    deliveryDate: "Monday",
    color: "Empire Red",
    capacity: "5 Quart",
    type: "Tilt-Head",
    warranty: "1 Year",
    lastPriceDrop: 0,
    priceDropDate: null,
    stockLeft: 15,
    isPriceWatched: false,
  },
];

// export default User;
export default User;
